# Generated by Django 5.2 on 2025-04-10 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('rpg', 'RPG'), ('fps', 'FPS'), ('adventure', 'Adventure'), ('strategy', 'Strategy'), ('puzzle', 'Puzzle'), ('platformer', 'Platformer'), ('metroidvania', 'Metroidvania'), ('visual_novel', 'Visual Novel'), ('other', 'Other')], max_length=20)),
                ('ambiance', models.CharField(choices=[('post_apocalyptic', 'Post-Apocalyptic'), ('fantasy', 'Fantasy'), ('cyberpunk', 'Cyberpunk'), ('scifi', 'Sci-Fi'), ('horror', 'Horror'), ('mystery', 'Mystery'), ('historical', 'Historical'), ('dreamlike', 'Dreamlike'), ('dark_fantasy', 'Dark Fantasy'), ('other', 'Other')], max_length=20)),
                ('keywords', models.CharField(max_length=200)),
                ('references', models.CharField(blank=True, max_length=200)),
                ('universe_description', models.TextField()),
                ('story_act1', models.TextField()),
                ('story_act2', models.TextField()),
                ('story_act3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('background', models.TextField()),
                ('abilities', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='games.game')),
            ],
        ),
    ]
