# Generated by Django 5.2 on 2025-04-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
