# Generated by Django 5.2 on 2025-04-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='has_dynamic_narrative',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NarrativeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('outcome_description', models.TextField()),
                ('act', models.IntegerField(choices=[(1, 'Acte 1'), (2, 'Acte 2'), (3, 'Acte 3')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_choices', to='games.game')),
            ],
        ),
    ]
