# Generated by Django 5.2 on 2025-04-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_has_dynamic_narrative_narrativechoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='NarrativeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('outcome_description', models.TextField()),
                ('act', models.IntegerField(choices=[(1, 'Acte 1'), (2, 'Acte 2'), (3, 'Acte 3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_history', to='games.game')),
            ],
            options={
                'verbose_name_plural': 'Narrative histories',
                'ordering': ['created_at'],
            },
        ),
    ]
